name = "map-frederic-dog"
compatibility_date = "2024-01-01"

[[r2_buckets]]
binding = "R2_BUCKET"
bucket_name = "map-dev"

[[d1_databases]]
binding = "dev_map"
database_name = "dev-map"
database_id = "31014eb9-78a0-4cba-ba39-bf1528ce15da"