name = "map-frederic-dog"
compatibility_date = "2024-01-01"

[[r2_buckets]]
binding = "R2_BUCKET"
bucket_name = "map-dev"

[[d1_databases]]
binding = "DB"
database_name = "map-auth"
database_id = "5cf5c86c-1cf7-4329-8895-9cd309dcfe11"

[vars]
WHITELIST_EMAILS = "fredmpoirier@gmail.com,frederic8242@gmail.com,emeryseheb@gmail.com"
